// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace PuppiesApi.Models
{
    public partial class Puppy
    {
        public int PuppyId { get; set; }
        public string Breed { get; set; }
        public string Name { get; set; }
        [DataType(DataType.Date)]

        public DateTime BirthDate { get; set; }
    }
}