// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PuppiesApi.Models
{
    public partial class Puppies
    {
        public int PuppyId { get; set; }
        public string Breed { get; set; }
        public string Name { get; set; }
        public DateTime? BirthDate { get; set; }
    }
}